eureka:
  instance:
    hostname: eureka
    insecurePort: 8761
    leaseRenewalIntervalInSeconds: 5 
    preferIpAddress: true
    prefer-ip-address: true
client:
  serviceUrl:
    defaultZone: http://eureka:8761/eureka/
