eureka:
  instance:
    hostname: eureka
    insecurePort: 8761
    leaseRenewalIntervalInSeconds: 5 
    preferIpAddress: false
    prefer-ip-address: false
client:
  serviceUrl:
    defaultZone: http://eureka:8761/eureka/
